### ISSUE TITLE
npm-offline unpacking results in FileNotFoundException

### ISSUE THREAD

**Issue by broundee** [allegro/grunt-maven-plugin#70]
Example exception:
```
Caused by: java.io.FileNotFoundException: /path/to/target/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/request-progress/.editorconfig (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at pl.allegro.tdr.gruntmaven.archive.TarUtil.untar(TarUtil.java:50)

```
Looks like the directory is not available when the file is being unpacked.

This could be fixed by adding the following to [this line](https://github.com/allegro/grunt-maven-plugin/blob/master/src/main/java/pl/allegro/tdr/gruntmaven/archive/TarUtil.java#L50)
```java
outputFile.getParentFile().mkdirs();
```

**Comment by adamdubiel** [comment]
Thanks, i will check this - any specific case? Because in normal use i never had problem with this.

**Comment by broundee** [comment]
Try this archive https://dl.dropboxusercontent.com/u/60305714/node_modules.tar
It was built with the following dependencies:
```
"devDependencies": {
    "grunt": "~0.4.5",
    "grunt-cli": "~0.1.13",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-contrib-requirejs": "~v0.4.4",
    "grunt-maven": "~1.2.0",
    "grunt-contrib-jshint": "~0.11.0",
    "requirejs": "~2.1.4",
    "karma": "~0.12.0",
    "karma-jasmine": "~0.2.0",
    "karma-phantomjs-launcher": "~0.1",
    "karma-requirejs": "~0.2",
    "grunt-karma": "~0.10.1"
  }
```
with the command
```bash
tar cf node_modules.tar node_modules/
```
on mac os x 10.10.2, tar version bsdtar 2.8.3 - libarchive 2.8.3.
I tested it with jdk 1.7.0_76 and 1.8.0_25.

**Comment by adamdubiel** [comment]
I just tried to repeat this error, but everything works fine. I'm using Ubuntu though. I just wonder why would the **FileNotFound** be thrown in such a place. Are you positive this will fix this issue on Mac? If so, i can add the line you are suggesting, i have to trust you on this one.

**Comment by broundee** [comment]
I've dug a bit deeper into this and found that the exception was thrown because entry.getName() returned child path, which did not start with "node_modules/".
To fix this I've changed the library from plexus-archiver to commons-compress, which returns correct entry name.

**Comment by broundee** [comment]
So, is this non-desirable to change archiving library? I suppose I can look for some workaround, but dependency update seems to me a better long-term solution.

**Comment by adamdubiel** [comment]
Hi, i didn't say it's undesirable, just didn't have time to take a good look at this. If it works, i'm for using this commons lib.

**Comment by ufukbay** [comment]
I think the problem we are having with npm-offline is related to this issue:
`/target-grunt/PaxHeader/node_modules (No such file or directory)`

Prepared the .tar file using `tar -cf node_modules.tar node_modules/` on Mac OS X 10.10.3

**Comment by omayevskiy** [comment]
The fix is already merged to master, can you please release it?
For us this issue is used if using 1.5.1-SNAPSHOT
many thx!

**Comment by adamdubiel** [comment]
Sure thing, I will release it later today.

**Comment by omayevskiy** [comment]
>adamdubiel commented 6 days ago
>Sure thing, I will release it later **today**.

can you please press the button ;-)

**Comment by adamdubiel** [comment]
Thats what happens when you got too much on your plate.. i just pulled the trigger, it's already on Github and will be available in Maven Central in couple hours, after it synces :)

**Comment by omayevskiy** [comment]
awesome, many thx!

    <plugin>
            <groupId>pl.allegro</groupId>
            <artifactId>grunt-maven-plugin</artifactId>
            --- <version>1.5.1-SNAPSHOT</version>
            +++ <version>1.5.1</version>
            ...
